name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: bash test/wtm_test.sh

      - name: Lint
        run: shellcheck bin/wtm test/wtm_test.sh
